// gen-metrics generates metrics.go from the files in
// github:Hopding/standard-fonts, which it assumes is checked out at
// ../standard-fonts.
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	var (
		fh  *os.File
		err error
	)
	if fh, err = os.Create("metrics.go"); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %s\n", err)
		os.Exit(1)
	}
	defer fh.Close()
	fmt.Fprintln(fh, "// Code generated by gen-metrics -- DO NOT EDIT.")
	fmt.Fprintln(fh, "package pdf")
	fmt.Fprintln(fh)
	fmt.Fprintln(fh, "var metrics = map[string]*fontMetrics{")
	for _, font := range []string{
		"Courier", "Courier-Bold", "Courier-Oblique", // "Courier-BoldOblique",
		"Helvetica", "Helvetica-Bold", "Helvetica-Oblique", // "Helvetica-BoldOblique",
		"Times-Bold", "Times-Italic", "Times-Roman", // "Times-BoldItalic",
		// "Symbol", "Zapf-Dingbats", (but don't use cp1252 for those)
	} {
		generateFontMetrics(fh, font)
	}
	fmt.Fprintln(fh, "}")
}

var cmLineRE = regexp.MustCompile(`^C -?\d+ ; WX (\d+) ; N (\S+) ; B -?\d+ (-?\d+) -?\d+ (-?\d+) ;((?: L \S+ \S+ ;)*)$`)
var kpLineRE = regexp.MustCompile(`^KPX (\S+) (\S+) (-?\d+)$`)

type charMetrics [3]int

func generateFontMetrics(out *os.File, font string) {
	var (
		fm     *os.File
		scan   *bufio.Scanner
		cms    map[string]charMetrics
		ligs   [][]string
		kps    [][]int
		habove int
		hbelow int
		err    error
	)
	if fm, err = os.Open("../standard-fonts/font_metrics/" + font + ".afm"); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %s\n", err)
		os.Exit(1)
	}
	defer fm.Close()
	scan = bufio.NewScanner(fm)
	cms = make(map[string]charMetrics)
	for scan.Scan() {
		if strings.HasPrefix(scan.Text(), "StartCharMetrics ") {
			break
		}
	}
	for scan.Scan() {
		line := scan.Text()
		if line == "EndCharMetrics" {
			break
		}
		if match := cmLineRE.FindStringSubmatch(line); match == nil {
			fmt.Fprintf(os.Stderr, "ERROR: %s: bad charmetrics line %q\n", font, line)
			os.Exit(1)
		} else {
			var cm charMetrics
			cm[0], _ = strconv.Atoi(match[1])
			cm[1], _ = strconv.Atoi(match[3])
			cm[2], _ = strconv.Atoi(match[4])
			cms[match[2]] = cm
			if match[5] != "" {
				for _, lig := range strings.Split(strings.TrimRight(match[5], ";"), ";") {
					fields := strings.Fields(lig)
					ligs = append(ligs, []string{match[2], fields[1], fields[2]})
				}
			}
		}
	}
	for scan.Scan() {
		line := scan.Text()
		if line == "EndFontMetrics" {
			goto noKern
		}
		if strings.HasPrefix(line, "StartKernPairs ") {
			break
		}
	}
	for scan.Scan() {
		line := scan.Text()
		if line == "EndKernPairs" {
			break
		}
		if match := kpLineRE.FindStringSubmatch(line); match == nil {
			fmt.Fprintf(os.Stderr, "ERROR: %s: bad kernpairs line %q\n", font, line)
			os.Exit(1)
		} else {
			c1 := cp1252map[match[1]]
			c2 := cp1252map[match[2]]
			if c1 == 0 || c2 == 0 {
				continue
			}
			delta, _ := strconv.Atoi(match[3])
			kps = append(kps, []int{int(c1), int(c2), delta})
		}
	}
noKern:
	fmt.Fprintf(out, "\t%q: {\n", font)
	fmt.Fprintln(out, "\t\tchars: [224]charMetrics{")
	for i := 32; i <= 255; i++ {
		if cp1252[i] == "" {
			fmt.Fprintln(out, "\t\t\t{0, 0, 0}, // UNUSED")
		} else if cm, ok := cms[cp1252[i]]; !ok {
			fmt.Fprintf(out, "\t\t\t{0, 0, 0}, // %s NOT DEFINED IN FONT\n", cp1252[i])
		} else {
			fmt.Fprintf(out, "\t\t\t{%d, %d, %d}, // %s\n", cm[0], cm[1], cm[2], cp1252[i])
			habove = max(habove, cm[2])
			hbelow = max(hbelow, -cm[1])
		}
	}
	fmt.Fprintln(out, "\t\t},")
	if len(ligs) != 0 {
		fmt.Fprintln(out, "\t\tligatures: map[[2]byte]charMetrics{")
		for _, lig := range ligs {
			b1 := cp1252map[lig[0]]
			b2 := cp1252map[lig[1]]
			cm := cms[lig[2]]
			if b1 == 0 || b2 == 0 || cm[0] == 0 {
				fmt.Fprintf(os.Stderr, "ERROR: %s: invalid ligature %q %q %q\n", font, lig[0], lig[1], lig[2])
			}
			fmt.Fprintf(out, "\t\t\t{%d, %d}: {%d, %d, %d},\n", rune(b1), rune(b2), cm[0], cm[1], cm[2])
			habove = max(habove, cm[2])
			hbelow = max(hbelow, -cm[1])
		}
		fmt.Fprintln(out, "\t\t},")
	}
	if len(kps) != 0 {
		fmt.Fprintln(out, "\t\tkernpairs: map[[2]byte]int16{")
		for _, kp := range kps {
			fmt.Fprintf(out, "\t\t\t{%d, %d}: %d,\n", kp[0], kp[1], kp[2])
		}
		fmt.Fprintln(out, "\t\t},")
	}
	fmt.Fprintf(out, "\t\thabove: %d,\n\t\thbelow: %d,\n", habove, hbelow)
	fmt.Fprintln(out, "\t},")
}
